name: "Android Build"
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      # ساخت کلید برای امضای اندروید
      - name: Create Debug Keystore
        run: |
          keytool -genkey -v -keystore debug.keystore -alias androiddebugkey -storepass android -keypass android -keyalg RSA -keysize 2048 -validity 10000 -dname "CN=Android Debug,O=Android,C=US"

      # استفاده از اکشن معتبر برای نصب گودو
      - name: Setup Godot
        uses: utgift/setup-godot@v1
        with:
          version: 4.2.1

      - name: Create Export Directory
        run: mkdir -p build/android

      - name: Godot Android Export
        run: |
          # معرفی مسیرها به گودو
          godot --headless --set-setting "export/android/android_sdk_path" "$ANDROID_SDK_ROOT"
          godot --headless --set-setting "export/android/debug_keystore" "$GITHUB_WORKSPACE/debug.keystore"
          # خروجی گرفتن
          godot --headless --export-debug "Android" build/android/game.apk

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Pantomime-Game-APK
          path: build/android/game.apk
          if-no-files-found: error
