name: "Android Build"
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Godot Android Export
        uses: firebelley/godot-export@v5.2.1
        with:
          godot_executable_download_url: https://github.com/godotengine/godot-builds/releases/download/4.2.1-stable/Godot_v4.2.1-stable_linux.x86_64.zip
          godot_export_templates_download_url: https://github.com/godotengine/godot-builds/releases/download/4.2.1-stable/Godot_v4.2.1-stable_export_templates.tpz
          relative_project_path: ./
          export_debug: true
          # اضافه کردن این خط برای اطمینان از مسیر خروجی
          relative_export_path: ./

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Pantomime-Game-APK
          path: ./*.apk
          if-no-files-found: error
