name: "Android Build Pipeline"
on: 
  push:
    branches: [ "main" ]

jobs:
  export-android:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Godot Android Export
        uses: firebelley/godot-export@v5.2.1
        with:
          # آدرس دانلود نسخه پایدار گودو
          godot_executable_download_url: https://downloads.tuxfamily.org/godotengine/4.2.1/Godot_v4.2.1-stable_linux_headless.64.zip
          godot_export_templates_download_url: https://downloads.tuxfamily.org/godotengine/4.2.1/Godot_v4.2.1-stable_export_templates.tpz
          relative_project_path: ./
          archive_output: true
          # تنظیمات خروجی اندروید
          export_debug: true
        env:
          RELATIVE_PATH_TO_PROJECT: ./

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Pantomime-Game-APK
          path: ./*.zip
